name: Update NPB Stats

on:
  schedule:
    - cron: "5,35 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Show execution time
        run: |
          echo "UTC=$(date -u)"
          echo "JST=$(TZ=Asia/Tokyo date)"
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests pandas beautifulsoup4 lxml html5lib

      - name: Check files
        run: |
          pwd
          ls -la

      - name: Run scraper
        run: python ./sap_site.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add public/npb_pitcher_stats_all.json

          git diff --cached --quiet || git commit -m "auto update"

          git push